### ISSUE TITLE
Cannot read properties of undefined (reading 'incoming')

### ISSUE THREAD

**Issue by cuibaoluo** [k8spacket/node-graph-plugin#1]
Hello, I can't use the node graph data source to display it using the josn api panel, which prompts this error
<img width="971" alt="image" src="https://user-images.githubusercontent.com/79293870/212244047-6b4b3b35-25e8-49e2-9995-c284bf092165.png">

**Comment by k8spacket** [comment]
Hi @cuibaoluo 

This plugin is not supported anymore. I suggest using this one: https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/

- is more flexible
- is publicly available (no need to allow grafana to install an unsigned plugin)
- is supported and updated

Best regards.
